modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/MichiJP/Trajectorys/issues"

[[mods]]
modId = "trajectorys"
version = "${file.jarVersion}"
displayName = "Trajectorys"
authors = "MichiJP"
description = '''
Display the trajectory of the launch section.
'''
logoFile = "icon.png"

[[dependencies.trajectorys]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trajectorys]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trajectorys]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0,)"
ordering = "NONE"
side = "CLIENT"